### ISSUE TITLE
Running start.rb results in an error

### ISSUE THREAD

**Issue by krnewsome** [realkdaigle/hello-treehouse#232]
Running start.rb after cloning the project results in a Ruby error.

OS X Yosemite 10.10.5

ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]

```
Reagans-Mac-Pro:hello-treehouse reagan$ ruby start.rb
Starting...
start.rb:5:in `<main>`: Don't start! It will explode! (RuntimeError)
```

**Comment by PetyaKatsarova** [comment]
same here: running start.rb after cloning the project results in ruby error. 

windows 8.1
ruby 2.4.2p198(2017-09-14 revision 59899) 

`$ ruby start.rb
start.rb:5:in '<main>': Don't start! It will explode! (RuntimeError)
Starting...
`
